language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install setuptools pip --upgrade
  - pip install -e .[test]
  - python -m ipykernel install --user
script:
  # cd so we test the install, not the repo
  - cd `mktemp -d`
  - pytest -v --maxfail=2 --cov=papermill --pyargs papermill
  - cd $TRAVIS_BUILD_DIR
  - python setup.py sdist bdist_wheel
  - python -m pip install --force-reinstall dist/papermill*.whl
  - python -m pip install --force-reinstall --no-deps dist/papermill*.tar.gz
after_success:
  - codecov
